Repository GSA/notifications-admin, pull requests merged in 2023-10, with the labels that each got.

#834 Production deploy 10/2/2023
  .github/workflows/checks.yml
  .github/workflows/daily_checks.yml
  app/assets/images/product/02-reporting-no-chrome.svg
  app/main/forms.py
  app/templates/components/table.html
  app/templates/views/service-settings.html
  app/templates/views/usage.html
  app/templates/views/user-profile.html
  docs/downloadable_reports.md
  docs/notify-pilot-info.md
  docs/sprint-goals.md
  poetry.lock
  tests/app/main/views/service_settings/test_service_settings.py
  tests/app/main/views/test_dashboard.py
  tests/app/main/views/test_templates.py
Labels: engineering

#846 822 - restrict international message services
  app/templates/views/service-settings.html
  tests/app/main/views/service_settings/test_service_settings.py
Labels: python, UI/UX

#890 Updated dependencies and add make command
  Makefile
  README.md
  poetry.lock
  pyproject.toml
Labels: engineering, security, dependencies
