Repository GSA/notifications-admin, pull requests merged in 2023-11, with the labels that each got.

#896 Update more dependencies and fix notifications-utils
  Makefile
  README.md
  poetry.lock
  pyproject.toml
Labels: documentation, engineering, dependencies

#907 Skip failing test for now in test_send.py
  tests/app/main/views/test_send.py
Labels: engineering, bug

#928 927 - Updates to math in Dashboard area
  app/__init__.py
  app/assets/javascripts/date.js
  app/templates/views/dashboard/_usage.html
  app/templates/views/dashboard/dashboard.html
  app/templates/views/usage.html
  gulpfile.js
  tests/app/main/views/test_dashboard.py
Labels: bug

#939 Update README with new instructions and improve setup
  .gitignore
  .pre-commit-config.yaml
  .python-version
  Makefile
  README.md
  poetry.lock
  pyproject.toml
  sample.env
Labels: documentation, engineering

#940 Update utils to 0.2.2
  poetry.lock
  tests/app/main/views/test_templates.py
Labels: engineering, dependencies

#954 Update cryptography dependency
  poetry.lock
Labels: engineering, security, dependencies

#953 Adjust positional arguments flagged by flake8-bugbear
  app/main/forms.py
  app/notify_client/status_api_client.py
Labels: engineering, dependencies, bug

#960 Update notifications-utils to 0.2.3
  poetry.lock
Labels: engineering, dependencies

#961 Prod deploy 11/30/2023
  poetry.lock
Labels: engineering
