Repository GSA/notifications-admin, pull requests merged in 2024-03, with the labels that each got.

#1273 Production Deploy 3/6/2024
  app/assets/sass/uswds/_uswds-theme-custom-styles.scss
  app/main/forms.py
  app/main/views/api_keys.py
  app/main/views/index.py
  app/main/views/manage_users.py
  app/main/views/performance.py
  app/main/views/send.py
  app/main/views/service_settings.py
  app/main/views/sub_navigation_dictionaries.py
  app/navigation.py
  app/templates/admin_template.html
  app/templates/components/components/header/template.njk
  app/templates/components/table.html
  app/templates/content_template.html
  app/templates/main_nav.html
  app/templates/partials/jobs/status.html
  app/templates/partials/notifications/notifications.html
  app/templates/settings_template.html
  app/templates/views/activity/notifications.html
  app/templates/views/api/callbacks.html
  app/templates/views/dashboard/_jobs.html
  app/templates/views/dashboard/dashboard.html
  app/templates/views/message-status.html
  app/templates/views/performance.html
  app/templates/views/usage.html
  app/templates/withnav_template.html
  tests/app/main/views/test_activity.py
  tests/app/main/views/test_index.py
  tests/app/main/views/test_jobs.py
  tests/app/test_navigation.py
Labels: engineering

#1280 Production Deploy 3/7/2024
  README.md
  app/main/views/jobs.py
Labels: engineering, bug

#1264 base.html created
  app/templates/new/base.html
  app/templates/new/layouts/org_template.html
  app/templates/new/layouts/withnav_template.html
  app/templates/new/templates_glossary.md
Labels: UI/UX

#1309 Update utils to 0.3.0
  poetry.lock
Labels: engineering, dependencies

#1278 Base template: <footer> #1259
  app/templates/admin_template.html
  app/templates/new/components/footer/footer.html
Labels: UI/UX

#1268 1216 login gov pre sign in page
  app/assets/javascripts/loginAlert.js
  app/assets/sass/uswds/_uswds-theme-custom-styles.scss
  app/templates/views/signin.html
  gulpfile.js
  tests/javascripts/loginAlert.test.js
Labels: engineering, UI/UX, javascript, redesign

#1312 Update Dependabot flagged dependencies
  poetry.lock
Labels: engineering, dependencies

#1313 Admin Production Deploy - 3/19/2024
  .github/workflows/deploy-demo.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy.yml
  app/assets/error_pages/5xx.html
  app/assets/images/android-chrome-192x192.png
  app/assets/images/android-chrome-256x256.png
  app/assets/images/apple-touch-icon.png
  app/assets/images/favicon-16x16.png
  app/assets/images/favicon-32x32.png
  app/assets/images/favicon.ico
  app/assets/images/mstile-150x150.png
  app/assets/images/notify-bell.svg
  app/assets/images/notify-dark-favicon.png
  app/assets/images/notify-logo-dark.svg
  app/assets/images/notify-logo.png
  app/assets/images/notify-logo.svg
  app/assets/images/notify-og-image.png
  app/assets/images/safari-pinned-tab.svg
  app/assets/images/site.webmanifest
  app/assets/javascripts/loginAlert.js
  app/assets/sass/uswds/_uswds-theme-custom-styles.scss
  app/config.py
  app/main/views/send.py
  app/templates/admin_template.html
  app/templates/components/components/header/template.njk
  app/templates/main_template.html
  app/templates/new/components/footer/footer.html
  app/templates/partials/jobs/notifications.html
  app/templates/views/signin.html
  gulpfile.js
  manifest.yml
  poetry.lock
  tests/app/test_utils.py
  tests/javascripts/loginAlert.test.js
Labels: engineering

#1327 Add missing env var from cf push
  .github/workflows/deploy-demo.yml
  .github/workflows/deploy-prod.yml
  app/main/views/sign_in.py
  tests/app/main/views/test_accept_invite.py
  tests/app/main/views/test_sign_in.py
  tests/app/test_utils.py
Labels: engineering, bug

#1329 Admin Production Deploy - 03/19/2024 (2)
  .github/workflows/deploy-demo.yml
  .github/workflows/deploy-prod.yml
  app/main/views/sign_in.py
  tests/app/main/views/test_accept_invite.py
  tests/app/main/views/test_sign_in.py
  tests/app/test_utils.py
Labels: engineering

#1342 Update Cloud Foundry runtime.txt file
  runtime.txt
Labels: engineering

#1345 Adjust E2E test fixtures
  tests/end_to_end/conftest.py
Labels: engineering

#1333 Edited style sheet to wrap long emails that overflow the parent div
  app/assets/sass/uswds/_uswds-theme-custom-styles.scss
Labels: UI/UX, Quick UI Fix

#1212 Create confirmation status alert (the last page in the preview send flow) #1211
  app/assets/sass/uswds/_legacy-styles.scss
  app/main/views/jobs.py
  app/main/views/send.py
  app/templates/partials/jobs/status.html
  app/templates/views/jobs/job.html
  tests/app/main/views/test_jobs.py
  tests/app/main/views/test_notifications.py
  tests/app/main/views/test_send.py
Labels: UI/UX, redesign

#1363 Reformat nested list in Login.gov documentation
  docs/login_dot_gov.md
Labels: documentation
