Repository GSA/notifications-admin, pull requests merged in 2024-02, with the labels that each got.

#1198 Production deploy 2/8/24
  app/__init__.py
  app/assets/images/product/security-review-message.png
  app/content/get-started.md
  app/main/views/notifications.py
  app/templates/components/table.html
  app/templates/views/guidance/index.html
  app/templates/views/roadmap.html
  app/templates/views/security.html
  app/templates/views/support/index.html
  app/utils/govuk_frontend_jinja/__init__.py
  app/utils/govuk_frontend_jinja/flask_ext.py
  app/utils/govuk_frontend_jinja/templates.py
  poetry.lock
  pyproject.toml
  tests/app/main/views/test_activity.py
  tests/app/main/views/test_jobs.py
Labels: engineering

#1202 Admin: Add a pull request template
  .github/pull_request_template.md
Labels: documentation, engineering

#1227 Production Deploy 2/20/2024
  .github/pull_request_template.md
  app/__init__.py
  app/assets/javascripts/collapsibleCheckboxes.js
  app/assets/sass/uswds/_uswds-theme-custom-styles.scss
  app/main/forms.py
  app/main/views/dashboard.py
  app/templates/views/dashboard/dashboard.html
  app/templates/views/signin.html
  app/utils/csv.py
  tests/app/main/forms/test_choose_time_form.py
  tests/app/main/views/test_api_integration.py
  tests/app/main/views/test_dashboard.py
  tests/app/utils/test_csv.py
  tests/conftest.py
Labels: engineering

#1233 Update utils to 0.2.9
  poetry.lock
Labels: engineering, security, dependencies

#772 Re-enable E2E GitHub action and get end-to-end tests working
  .github/workflows/checks.yml
  Makefile
  app/config.py
  tests/conftest.py
  tests/end_to_end/__init__.py
  tests/end_to_end/conftest.py
  tests/end_to_end/test_accounts_page.py
  tests/end_to_end/test_landing_and_sign_in_pages.py
Labels: engineering

#1238 Add E2E documentation and clean E2E tests
  docs/end_to_end_tests.md
  tests/app/main/views/test_manage_users.py
  tests/app/main/views/test_template_folders.py
  tests/conftest.py
  tests/end_to_end/conftest.py
  tests/end_to_end/test_accounts_page.py
  tests/end_to_end/test_landing_and_sign_in_pages.py
Labels: documentation, engineering

#1244 Filtered out empty notifications (related to recent batch table)
  app/main/views/dashboard.py
Labels: bug, UI/UX, Quick UI Fix

#1226 Quick fix: added padding to td on recent table table
  app/assets/sass/uswds/_uswds-theme-custom-styles.scss
Labels: Quick UI Fix

#1249 2/27/2024 Production Deployment
  .github/workflows/checks.yml
  .github/workflows/deploy-demo.yml
  .github/workflows/deploy.yml
  Makefile
  app/assets/sass/uswds/_uswds-theme-custom-styles.scss
  app/config.py
  app/main/views/dashboard.py
  app/main/views/sign_in.py
  app/templates/views/guidance/index.html
  app/templates/views/pricing/index.html
  app/templates/views/roadmap.html
  app/templates/views/security.html
  app/templates/views/support/index.html
  app/utils/csv.py
  deploy-config/egress_proxy/notify-admin-demo.allow.acl
  deploy-config/egress_proxy/notify-admin-production.allow.acl
  docs/end_to_end_tests.md
  poetry.lock
  pyproject.toml
  tests/app/main/views/test_dashboard.py
  tests/app/main/views/test_manage_users.py
  tests/app/main/views/test_sign_in.py
  tests/app/main/views/test_template_folders.py
  tests/app/utils/test_csv.py
  tests/conftest.py
  tests/end_to_end/__init__.py
  tests/end_to_end/conftest.py
  tests/end_to_end/test_accounts_page.py
  tests/end_to_end/test_landing_and_sign_in_pages.py
Labels: engineering
