Repository GSA/notifications-admin, pull requests merged in 2024-12, with the labels that each got.

#2178 Add youtube video to about page
  app/__init__.py
  app/templates/views/about/about.html
Labels: Content

#2128 New Contact page
  app/main/views/index.py
  app/main/views/sub_navigation_dictionaries.py
  app/templates/views/contact.html
  tests/app/test_navigation.py
Labels: Content, UI/UX

#2192 Added errors focus to empty field
  app/main/views/send.py
  app/templates/views/check/ok.html
  app/templates/views/check/preview.html
  app/templates/views/send-test.html
Labels: a11y

#2197 2133 small a11y updates
  app/templates/components/components/back-link/template.njk
  app/templates/components/folder-path.html
  app/templates/partials/jobs/status.html
  app/templates/views/check/preview.html
  app/templates/views/send.html
  app/templates/views/templates/_template.html
  app/templates/views/templates/template.html
  tests/app/main/views/test_templates.py
Labels: a11y

#2228 Bump jinja2 from 3.1.4 to 3.1.5
  poetry.lock
  pyproject.toml
Labels: engineering, dependencies

#2222 2072 - Benefits Studio About Page
  app/main/views/index.py
  app/main/views/send.py
  app/templates/components/footer.html
  app/templates/views/studio.html
  tests/app/test_navigation.py
Labels: Content
