Repository GSA/notifications-admin, pull requests merged in 2024-04, with the labels that each got.

#1364 Admin Production Deploy - 3/28/2024
  .github/actions/setup-project/action.yml
  README.md
  app/__init__.py
  app/assets/sass/uswds/_legacy-styles.scss
  app/assets/sass/uswds/_uswds-theme-custom-styles.scss
  app/formatters.py
  app/main/forms.py
  app/main/views/index.py
  app/main/views/jobs.py
  app/main/views/register.py
  app/main/views/send.py
  app/main/views/sign_in.py
  app/main/views/sign_out.py
  app/main/views/verify.py
  app/notify_client/user_api_client.py
  app/templates/components/components/select/README.md
  app/templates/components/components/select/macro-options.json
  app/templates/components/components/select/macro.njk
  app/templates/components/components/select/template.njk
  app/templates/components/table.html
  app/templates/error/401.html
  app/templates/new/base.html
  app/templates/new/components/head/head.html
  app/templates/new/templates_glossary.md
  app/templates/partials/jobs/status.html
  app/templates/views/api/keys.html
  app/templates/views/dashboard/dashboard.html
  app/templates/views/jobs/job.html
  app/templates/views/platform-admin/complaints.html
  app/templates/views/set-up-your-profile.html
  app/templates/views/signedout.html
  app/utils/__init__.py
  docs/login_dot_gov.md
  poetry.lock
  pyproject.toml
  runtime.txt
  tests/app/main/views/service_settings/test_service_settings.py
  tests/app/main/views/test_api_integration.py
  tests/app/main/views/test_dashboard.py
  tests/app/main/views/test_find_users.py
  tests/app/main/views/test_jobs.py
  tests/app/main/views/test_notifications.py
  tests/app/main/views/test_performance.py
  tests/app/main/views/test_register.py
  tests/app/main/views/test_send.py
  tests/app/models/test_base_model.py
  tests/app/notify_client/test_template_folder_client.py
  tests/app/test_navigation.py
  tests/end_to_end/conftest.py
Labels: engineering

#1383 Update several recent dependencies
  Makefile
  poetry.lock
  pyproject.toml
Labels: engineering, dependencies

#1385 Update GitHub Actions
  .github/workflows/checks.yml
  .github/workflows/daily_checks.yml
  .github/workflows/deploy-demo.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy.yml
  .github/workflows/drift.yml
  .github/workflows/terraform-demo.yml
  .github/workflows/terraform-production.yml
  .github/workflows/terraform-staging.yml
Labels: engineering, security, dependencies

#1400 Update utils to 0.4.5
  poetry.lock
  pyproject.toml
Labels: engineering, dependencies

#1406 Tests with timezone checks are failing locally
  app/__init__.py
  app/formatters.py
  app/main/views/send.py
  app/templates/views/check/preview.html
  app/templates/views/notifications/preview.html
  app/utils/templates.py
  app/utils/time.py
  tests/app/main/views/test_send.py
Labels: bug

#1419 Update utils to 0.4.6
  poetry.lock
  tests/app/main/forms/test_placeholder_form.py
  tests/app/main/views/test_dashboard.py
Labels: engineering, dependencies

#1426 Updated dependencies and ignore gunicorn audit flag
  .github/workflows/checks.yml
  poetry.lock
Labels: engineering, security, dependencies

#1399 1269 - Content updates for Service Settings after login.gov integration
  app/templates/views/service-settings/set-auth-type.html
  poetry.lock
  tests/app/main/views/service_settings/test_service_settings.py
Labels: Content

#1440 04/17/2024 Production Deploy
  .github/workflows/checks.yml
  Makefile
  app/__init__.py
  app/formatters.py
  app/main/views/dashboard.py
  app/main/views/platform_admin.py
  app/main/views/send.py
  app/main/views/sign_in.py
  app/templates/error/500.html
  app/templates/new/components/main_nav.html
  app/templates/new/components/org_nav.html
  app/templates/new/components/service_navigation.html
  app/templates/new/components/settings_navigation.html
  app/templates/new/layouts/org_template.html
  app/templates/new/layouts/withnav_template.html
  app/templates/new/templates_glossary.md
  app/templates/views/check/preview.html
  app/templates/views/notifications/preview.html
  app/templates/views/service-settings/set-auth-type.html
  app/templates/views/set-up-your-profile.html
  app/templates/views/signin.html
  app/templates/views/user-profile.html
  app/utils/templates.py
  app/utils/time.py
  poetry.lock
  tests/app/main/forms/test_placeholder_form.py
  tests/app/main/views/organizations/test_organizations.py
  tests/app/main/views/service_settings/test_service_settings.py
  tests/app/main/views/test_accept_invite.py
  tests/app/main/views/test_dashboard.py
  tests/app/main/views/test_send.py
  tests/app/main/views/test_sign_in.py
  tests/app/utils/test_time.py
  tests/conftest.py
  tests/end_to_end/test_create_new_template.py
  tests/end_to_end/test_send_message_from_existing_template.py
Labels: engineering

#1458 Update exceptiongroup and newrelic packages
  poetry.lock
  pyproject.toml
Labels: engineering, dependencies

#1418 revised withnav_templates to include org_template
  app/templates/new/components/org_nav.html
  app/templates/new/components/org_nav_breadcrumb.html
  app/templates/new/layouts/org_template.html
  app/templates/new/layouts/withnav_template.html
Labels: UI/UX

#1483 4/26/2024 Production Deploy
  app/main/views/register.py
  app/main/views/sign_in.py
  app/main/views/verify.py
  app/notify_client/service_api_client.py
  app/templates/new/components/org_nav.html
  app/templates/new/components/org_nav_breadcrumb.html
  app/templates/new/layouts/org_template.html
  app/templates/new/layouts/withnav_template.html
  app/templates/views/manage-users.html
  app/templates/views/service-settings.html
  app/templates/views/user-profile.html
  manifest.yml
  poetry.lock
  pyproject.toml
  tests/app/main/views/organizations/test_organization_invites.py
  tests/app/main/views/service_settings/test_service_settings.py
  tests/app/main/views/test_accept_invite.py
  tests/app/main/views/test_manage_users.py
  tests/app/main/views/test_register.py
  tests/app/main/views/test_verify.py
  tests/end_to_end/test_invite_team_member_to_service.py
Labels: engineering
