Repository GSA/notifications-admin, pull requests merged in 2024-08, with the labels that each got.

#1800 Update dependabot.yml config
  .github/dependabot.yml
Labels: engineering, github_actions

#1852 Fix formatting in production main.tf file
  terraform/production/main.tf
Labels: engineering

#1879 Production Deploy 8/19/2024
  .github/dependabot.yml
  app/assets/javascripts/activityChart.js
  app/assets/sass/uswds/_data-visualization.scss
  app/templates/views/activity/all-activity.html
  poetry.lock
Labels: engineering

#1885 updated url for close.svg
  app/templates/new/components/header.html
Labels: Quick UI Fix
