Repository GSA/notifications-admin, pull requests merged in 2024-05, with the labels that each got.

#1511 Updating several dependencies related to Flask upgrade
  poetry.lock
  pyproject.toml
Labels: engineering, dependencies

#1517 Update several dependencies from Dependabot
  poetry.lock
  pyproject.toml
Labels: engineering, dependencies

#1537 Update dependencies (05/14/2024)
  poetry.lock
  pyproject.toml
Labels: engineering, dependencies

#1538 Updated config files to split the cloud foundry and public admin routes
  deploy-config/demo.yml
  deploy-config/production.yml
  deploy-config/sandbox.yml
  deploy-config/staging.yml
  manifest.yml
Labels: engineering, redesign

#1548 Add missing dependencies
  poetry.lock
  pyproject.toml
Labels: engineering, dependencies, python

#1553 Update pre-commit hooks
  .ds.baseline
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
Labels: engineering, security, dependencies

#1569 Update Python dependencies
  poetry.lock
  pyproject.toml
Labels: engineering, dependencies, python

#1577 Update admin repo dependencies
  poetry.lock
  pyproject.toml
Labels: engineering, dependencies, python

#1502 Updated filename string into db for a notification and UI display
  app/main/views/send.py
  app/templates/views/dashboard/dashboard.html
Labels: engineering, bug, python, UI/UX, Quick UI Fix

#1581 Update dependencies and fix E2E test
  poetry.lock
  pyproject.toml
  tests/end_to_end/test_send_message_from_existing_template.py
Labels: engineering, dependencies, python
