Repository GSA/notifications-admin, pull requests merged in 2024-11, with the labels that each got.

#2076 Template voiceover gets stuck in a loop #2056
  app/templates/views/templates/_template_list.html
  app/templates/views/templates/choose.html
Labels: a11y

#2093 Fix Login.gov sign in URL formatting for staging
  .github/workflows/deploy.yml
  tests/end_to_end/test_send_message_from_existing_template.py
Labels: engineering

#2127 About Security Content
  app/main/views/index.py
  app/main/views/sub_navigation_dictionaries.py
  app/templates/views/about/security.html
  tests/app/test_navigation.py
Labels: Content, UI/UX

#2163 Bump admin production memory to 2GB per instance
  deploy-config/production.yml
Labels: engineering
