Repository GSA/notifications-admin, pull requests merged in 2024-07, with the labels that each got.

#1680 Update pull request template
  .github/pull_request_template.md
Labels: documentation, engineering

#1688 07/02/2024 Production Release
  .github/pull_request_template.md
  .nvmrc
  README.md
  app/main/views/send.py
  package-lock.json
  package.json
  poetry.lock
  pyproject.toml
  sample.env
Labels: engineering

#1691 Update Python dependencies - 7/2/2024
  poetry.lock
  pyproject.toml
Labels: engineering, dependencies, python

#1700 Update Python Dependencies - 7/5/2024
  poetry.lock
  pyproject.toml
Labels: engineering, dependencies, python

#1704 07/05/2024 Production Deploy
  app/assets/javascripts/sampleChartDashboard.js
  app/assets/sass/uswds/_legacy-styles.scss
  app/main/views/dashboard.py
  app/main/views/tour.py
  app/notify_client/service_api_client.py
  app/templates/views/dashboard/dashboard.html
  app/templates/views/notifications/preview.html
  gulpfile.js
  gunicorn_config.py
  package-lock.json
  package.json
  poetry.lock
  pyproject.toml
  tests/app/main/views/test_dashboard.py
  tests/app/main/views/test_tour.py
  tests/end_to_end/test_send_message_from_existing_template.py
Labels: engineering

#1720 Update Python dependencies - 7/12/24 - and ignore idna pip-audit flag
  .github/workflows/checks.yml
  poetry.lock
  pyproject.toml
Labels: engineering, dependencies, python

#1726 Update Python dependencies - 7/16/24
  poetry.lock
  pyproject.toml
Labels: engineering, dependencies, python

#1729 07/16/2024 Production Deploy
  .ds.baseline
  .github/workflows/checks.yml
  app/main/views/dashboard.py
  app/main/views/jobs.py
  app/main/views/sign_out.py
  app/main/views/verify.py
  app/models/user.py
  app/notify_client/__init__.py
  app/notify_client/user_api_client.py
  poetry.lock
  pyproject.toml
  terraform/README.md
  terraform/bootstrap/main.tf
  terraform/sandbox/main.tf
  tests/app/main/test_errorhandlers.py
  tests/app/main/views/accounts/test_choose_accounts.py
  tests/app/main/views/accounts/test_show_accounts_or_dashboard.py
  tests/app/main/views/organizations/test_organization_invites.py
  tests/app/main/views/test_accept_invite.py
  tests/app/main/views/test_dashboard.py
  tests/app/main/views/test_headers.py
  tests/app/main/views/test_index.py
  tests/app/main/views/test_platform_admin.py
  tests/app/main/views/test_register.py
  tests/app/main/views/test_sign_in.py
  tests/app/main/views/test_sign_out.py
  tests/app/main/views/test_two_factor.py
  tests/app/main/views/test_verify.py
  tests/app/notify_client/test_service_api_client.py
  tests/app/utils/test_user.py
Labels: engineering

#1747 Python dependency updates - 7/22/24
  poetry.lock
  pyproject.toml
Labels: engineering, dependencies, python

#1751 Increased Admin app memory to 4 GB
  deploy-config/production.yml
Labels: engineering

#1760 Update Python runtime version for cloud.gov
  runtime.txt
Labels: engineering, python

#1762 fixed image
  app/assets/images/product/phone-text.svg
  app/templates/views/signedout.html
Labels: Quick UI Fix

#1764 Revert "fixed image" - swap image from svg back to png
  app/assets/images/product/phone-text.svg
  app/templates/views/signedout.html
Labels: engineering

#1765 7/24/2024 Production Deploy
  .ds.baseline
  .github/workflows/checks.yml
  .gitignore
  app/__init__.py
  app/main/forms.py
  app/main/validators.py
  app/main/views/dashboard.py
  app/main/views/send.py
  app/models/user.py
  app/notify_client/__init__.py
  app/templates/new/components/footer.html
  app/templates/new/components/header.html
  app/templates/partials/jobs/status.html
  app/templates/views/dashboard/dashboard.html
  deploy-config/production.yml
  gulpfile.js
  package-lock.json
  package.json
  poetry.lock
  pyproject.toml
  runtime.txt
  terraform/bootstrap/main.tf
  terraform/bootstrap/providers.tf
  terraform/demo/main.tf
  terraform/development/main.tf
  terraform/production/main.tf
  terraform/sandbox/main.tf
  terraform/staging/main.tf
  tests/app/main/views/accounts/test_choose_accounts.py
  tests/app/main/views/service_settings/test_service_setting_permissions.py
  tests/app/main/views/service_settings/test_service_settings.py
  tests/app/main/views/test_accept_invite.py
  tests/app/main/views/test_dashboard.py
  tests/app/main/views/test_two_factor.py
  tests/app/models/test_template_list.py
  tests/app/s3_client/test_s3_logo_client.py
  tests/app/test_cloudfoundry_config.py
  tests/app/utils/test_csv.py
  tests/app/utils/test_user.py
  tests/conftest.py
  tests/end_to_end/conftest.py
  tests/notifications_utils/clients/redis/test_redis_client.py
  tests/notifications_utils/clients/redis/test_request_cache.py
  tests/notifications_utils/conftest.py
Labels: engineering

#1775 7/25/2024 Follow-up production release
  deploy-config/production.yml
Labels: engineering

#1785 Update Python dependencies - 7/30/24
  poetry.lock
  pyproject.toml
Labels: engineering, dependencies, python
