Repository GSA/notifications-admin, pull requests merged in 2025-05, with the labels that each got.

#2518 2514 - Removing colourPreview.js
  app/assets/javascripts/colourPreview.js
  gulpfile.js
  tests/javascripts/colourPreview.test.js
Labels: engineering, javascript

#2522 2515 - Remove autofocus.js
  app/assets/javascripts/autofocus.js
  app/assets/sass/uswds/_main.scss
  app/templates/components/live-search.html
  app/templates/views/manage-users.html
  app/templates/views/organizations/organization/users/index.html
  gulpfile.js
  tests/app/main/views/organizations/test_organizations.py
  tests/app/main/views/test_manage_users.py
  tests/javascripts/autofocus.test.js
Labels: engineering, javascript

#2521 2517 - Removing timeago.js
  app/assets/javascripts/main.js
  app/templates/views/api/index.html
  app/templates/views/find-users/user-information.html
  gulpfile.js
  package-lock.json
  package.json
Labels: engineering, javascript

#2519 2515 - remove homepage.js
  app/assets/javascripts/homepage.js
  gulpfile.js
Labels: engineering, javascript

#2424 Fix existing end-to-end tests
  .ds.baseline
  .github/workflows/checks.yml
  Makefile
  app/assets/stylesheets/main.scss
  app/main/views/index.py
  app/main/views/jobs.py
  app/templates/components/components/input/template.njk
  app/utils/api_health.py
  app/utils/csv.py
  backstop_data/bitmaps_reference/backstop_test_Choose_Service_-_Accounts_1_ausa-buttonhrefadd-service_0_desktop.png
  backstop_data/bitmaps_reference/backstop_test_Establish_Trust_0_document_0_desktop.png
  poetry.lock
  tests/app/main/views/service_settings/test_service_settings.py
  tests/app/main/views/test_manage_users.py
  tests/app/main/views/test_register.py
  tests/app/main/views/test_tour.py
  tests/end_to_end/conftest.py
  tests/end_to_end/test_create_new_template.py
  tests/notifications_utils/conftest.py
Labels: engineering

#2564 Update no_proxy environment variable
  .profile
Labels: engineering

#2569 Pin egress proxy release
  .ds.baseline
  .github/actions/deploy-proxy/action.yml
Labels: engineering, github_actions

#2559 05/07/2025 Production Deploy
  .ds.baseline
  .github/actions/deploy-proxy/action.yml
  .github/actions/setup-project/action.yml
  .github/workflows/checks.yml
  .profile
  Makefile
  app/__init__.py
  app/assets/javascripts/autofocus.js
  app/assets/javascripts/colourPreview.js
  app/assets/javascripts/homepage.js
  app/assets/javascripts/main.js
  app/assets/sass/uswds/_main.scss
  app/assets/stylesheets/main.scss
  app/main/views/index.py
  app/main/views/jobs.py
  app/main/views/send.py
  app/main/views/tour.py
  app/s3_client/s3_csv_client.py
  app/templates/components/components/back-link/macro.njk
  app/templates/components/components/back-link/template.njk
  app/templates/components/components/input/template.njk
  app/templates/components/live-search.html
  app/templates/views/api/index.html
  app/templates/views/check/ok.html
  app/templates/views/check/preview.html
  app/templates/views/edit-sms-template.html
  app/templates/views/find-users/user-information.html
  app/templates/views/manage-users.html
  app/templates/views/notifications/check.html
  app/templates/views/notifications/preview.html
  app/templates/views/organizations/organization/users/index.html
  app/templates/views/send-test.html
  app/templates/views/send.html
  app/utils/api_health.py
  app/utils/csv.py
  backstop_data/bitmaps_reference/backstop_test_Choose_Service_-_Accounts_1_ausa-buttonhrefadd-service_0_desktop.png
  backstop_data/bitmaps_reference/backstop_test_Establish_Trust_0_document_0_desktop.png
  docs/Meeting 7 Slides - T&N (1).pdf
  gulpfile.js
  package-lock.json
  package.json
  poetry.lock
  pyproject.toml
  pytest.ini
  tests/app/main/views/organizations/test_organizations.py
  tests/app/main/views/service_settings/test_service_settings.py
  tests/app/main/views/test_headers.py
  tests/app/main/views/test_manage_users.py
  tests/app/main/views/test_register.py
  tests/app/main/views/test_send.py
  tests/app/main/views/test_tour.py
  tests/app/s3_client/test_s3_csv_client.py
  tests/end_to_end/conftest.py
  tests/end_to_end/test_create_new_template.py
  tests/javascripts/autofocus.test.js
  tests/javascripts/colourPreview.test.js
  tests/notifications_utils/conftest.py
Labels: engineering

#2567 2211 - Update content to inform user of page refresh
  app/templates/views/jobs/job.html
  tests/app/main/views/test_jobs.py
Labels: Content

#2558 2554 add cancel button and modal to preview send page
  app/assets/javascripts/notifyModal.js
  app/assets/javascripts/preventDuplicateFormSubmissions.js
  app/assets/js/init.uswds.js
  app/assets/sass/uswds/_main.scss
  app/templates/base.html
  app/templates/components/components/button/template.njk
  app/templates/views/check/ok.html
  app/templates/views/notifications/check.html
  app/templates/views/notifications/preview.html
  app/templates/views/platform-admin/index.html
  gulpfile.js
  tests/javascripts/notifyModal.test.js
  tests/javascripts/timeoutPopup.test.js
Labels: engineering, UI/UX, javascript, a11y

#2578 2568 - Clean up CSS
  app/assets/javascripts/radioSelect.js
  app/assets/sass/uswds/_main.scss
  app/assets/sass/uswds/_uswds-theme-custom-styles.scss
  app/templates/base.html
  app/templates/views/find-services/find-services-by-name.html
  app/templates/views/find-users/find-users-by-email.html
  app/templates/views/manage-users.html
  tests/app/main/views/test_manage_users.py
  tests/javascripts/radioSelect.test.js
Labels: UI/UX, UI Cosmetic Fix

#2596 Clean up typos
  README.md
  docs/docker-remote-containers.md
  docs/feature-flagging.md
  docs/sprint-goals.md
  notifications_utils/clients/redis/redis_client.py
  notifications_utils/formatters.py
  notifications_utils/insensitive_dict.py
  notifications_utils/international_billing_rates.yml
  notifications_utils/recipients.py
  notifications_utils/serialised_model.py
  notifications_utils/template.py
Labels: documentation

#2622 Updated pip-audit ignore-vulns
  .github/workflows/checks.yml
  .github/workflows/daily_checks.yml
Labels: engineering, dependencies, python
