Repository GSA/notifications-admin, pull requests merged in 2025-06, with the labels that each got.

#2645 Unpin egress proxy release and update eventlet dependency
  .ds.baseline
  .github/actions/deploy-proxy/action.yml
  poetry.lock
  pyproject.toml
Labels: engineering, dependencies, github_actions

#2663 Fixes for several bugs on the templates page related to form submission issues
  app/assets/javascripts/liveSearch.js
  app/assets/javascripts/templateFolderForm.js
  app/assets/sass/uswds/_uswds-theme-custom-styles.scss
  app/templates/views/templates/choose-reply.html
  app/templates/views/templates/choose.html
  app/templates/views/templates/copy.html
  tests/javascripts/liveSearch.test.js
Labels: UI/UX

#2676 06/12/25 Production Deploy
  .ds.baseline
  .github/actions/deploy-proxy/action.yml
  .github/actions/setup-project/action.yml
  app/assets/images/messaging-devices.svg
  app/assets/javascripts/liveSearch.js
  app/assets/javascripts/templateFolderForm.js
  app/assets/pdf/Studio Research & Development.pdf
  app/assets/pdf/The Notify Story.pdf
  app/assets/sass/uswds/_uswds-theme-custom-styles.scss
  app/notify_client/service_api_client.py
  app/templates/base.html
  app/templates/components/header.html
  app/templates/views/signedout.html
  app/templates/views/templates/choose-reply.html
  app/templates/views/templates/choose.html
  app/templates/views/templates/copy.html
  assets/uswds/components/usa-banner.js.mjs
  assets/uswds/components/usa-banner.js.umd.js
  gulpfile.js
  manifest.yml
  package-lock.json
  package.json
  poetry.lock
  pyproject.toml
  tests/app/main/views/test_sign_in.py
  tests/app/main/views/test_templates.py
  tests/end_to_end/test_create_new_template.py
  tests/end_to_end/test_landing_and_sign_in_pages.py
  tests/javascripts/liveSearch.test.js
Labels: engineering

#2707 Improve folder permissions on invite team member page:
  app/assets/javascripts/collapsibleCheckboxes.js
  app/assets/sass/uswds/_uswds-theme-custom-styles.scss
  app/main/views/manage_users.py
  tests/javascripts/collapsibleCheckboxes.test.js
Labels: UI/UX
