Repository GSA/notifications-admin, pull requests merged in 2025-01, with the labels that each got.

#2247 2227 - Adding Acceptable Use Policy page
  app/main/views/index.py
  app/templates/components/footer.html
  app/templates/components/header.html
  app/templates/views/acceptable-use-policy.html
  tests/app/test_navigation.py
Labels: Content

#2276 adjust styling and content cards
  app/assets/sass/uswds/_legacy-styles.scss
  app/templates/views/about/why-text-messaging.html
Labels: Content, UI Cosmetic Fix

#2278 01/17/2025 Production Deploy hotfix
  app/assets/sass/uswds/_legacy-styles.scss
  app/templates/views/about/why-text-messaging.html
Labels: engineering, UI Cosmetic Fix

#2288 Update no-cost service details
  app/templates/views/join-notify.html
Labels: Content

#2266 Updating/Fix job status states
  app/assets/javascripts/activityChart.js
  app/main/views/dashboard.py
  app/templates/views/dashboard/activity-table.html
  app/templates/views/dashboard/dashboard.html
  tests/app/main/views/test_dashboard.py
  tests/javascripts/activityChart.test.js
Labels: UI/UX

#2271 1706 updaterevise status banner on confirmation page
  app/main/views/jobs.py
  app/templates/partials/jobs/status.html
  app/templates/views/jobs/job.html
Labels: UI/UX

#2250 Add pending to dashboard
  app/assets/javascripts/activityChart.js
  app/main/views/dashboard.py
  app/templates/views/dashboard/activity-table.html
  package-lock.json
  package.json
  tests/javascripts/activityChart.test.js
Labels: UI/UX

#2313 Update zaproxy-baseline GitHub Action reference
  .github/workflows/checks.yml
  .github/workflows/daily_checks.yml
Labels: engineering, github_actions
