Repository GSA/notifications-admin, pull requests merged in 2025-04, with the labels that each got.

#2486 2041 csv upload more instructions
  app/assets/sass/uswds/_legacy-styles.scss
  app/templates/components/file-upload.html
  app/templates/views/send.html
Labels: Content

#2520 bug - Update activityChart.test.js
  tests/javascripts/activityChart.test.js
Labels: bug, javascript

#2440 2138 - Change cancel button to uploading button for CSV
  app/assets/javascripts/fileUpload.js
  app/assets/javascripts/fullscreenTable.js
  app/assets/sass/uswds/_main.scss
  app/assets/sass/uswds/styles.scss
  app/templates/base.html
  app/templates/components/banner.html
  app/templates/components/file-upload.html
  app/templates/views/check/column-errors.html
  app/templates/views/check/ok.html
  app/templates/views/check/row-errors.html
  app/templates/views/send.html
  tests/javascripts/fileUpload.domLoad.test.js
  tests/javascripts/fileUpload.test.js
  tests/javascripts/fullscreenTable.test.js
Labels: engineering, javascript, a11y

#2537 Remove hint text and country code reference
  app/templates/views/send-test.html
  tests/app/main/views/test_send.py
Labels: bug, Content

#2533 04/24/2025 Production Deploy
  .ds.baseline
  .github/workflows/checks.yml
  .gitignore
  Makefile
  app/__init__.py
  app/assets/images/api-error.svg
  app/assets/javascripts/fileUpload.js
  app/assets/javascripts/fullscreenTable.js
  app/assets/javascripts/socketio.js
  app/assets/pdf/wa_case_study.pdf
  app/assets/sass/uswds/_main.scss
  app/assets/sass/uswds/_uswds-theme-custom-styles.scss
  app/assets/sass/uswds/styles.scss
  app/config.py
  app/main/views/index.py
  app/main/views/jobs.py
  app/main/views/send.py
  app/templates/base.html
  app/templates/components/banner.html
  app/templates/components/file-upload.html
  app/templates/components/textbox.html
  app/templates/error/technical_difficulties.html
  app/templates/views/check/column-errors.html
  app/templates/views/check/ok.html
  app/templates/views/check/row-errors.html
  app/templates/views/jobs/job.html
  app/templates/views/send-test.html
  app/templates/views/send.html
  app/templates/views/signedout.html
  app/utils/api_health.py
  deploy-config/demo.yml
  deploy-config/production.yml
  deploy-config/sandbox.yml
  deploy-config/staging.yml
  gulpfile.js
  manifest.yml
  notifications_utils/logging.py
  notifications_utils/markdown.py
  package-lock.json
  package.json
  poetry.lock
  pyproject.toml
  tests/app/main/views/test_headers.py
  tests/app/main/views/test_index.py
  tests/app/main/views/test_templates.py
  tests/app/main/views/test_tour.py
  tests/javascripts/activityChart.test.js
  tests/javascripts/fileUpload.domLoad.test.js
  tests/javascripts/fileUpload.test.js
  tests/javascripts/fullscreenTable.test.js
Labels: engineering
