Repository GSA/notifications-admin, pull requests merged in 2025-03, with the labels that each got.

#2273 2200 - Adding tooltip to Total messages header for explanation
  app/assets/sass/uswds/_data-visualization.scss
  app/assets/sass/uswds/_uswds-theme-custom-styles.scss
  app/templates/views/dashboard/dashboard.html
Labels: Content, UI/UX, a11y, user concern

#2356 2214 client side validation
  app/__init__.py
  app/assets/javascripts/validation.js
  app/assets/sass/uswds/_uswds-theme-custom-styles.scss
  app/main/views/send.py
  app/templates/components/components/input/template.njk
  app/templates/components/components/label/template.njk
  app/templates/components/file-upload.html
  app/templates/components/radios.html
  app/templates/components/select-input.html
  app/templates/components/textbox.html
  app/templates/views/send-test.html
  gulpfile.js
  tests/app/main/views/organizations/test_organizations.py
  tests/app/main/views/service_settings/test_service_settings.py
  tests/app/main/views/test_activity.py
  tests/app/main/views/test_manage_users.py
  tests/app/main/views/test_register.py
  tests/app/main/views/test_send.py
  tests/app/main/views/test_tour.py
  tests/javascripts/validation.test.js
Labels: engineering, UI/UX, javascript, a11y

#2399 2398 - broken TTS link
  app/templates/base.html
Labels: bug

#2397 2391 - Updating Cross Origin code to allow Youtube
  notifications_utils/request_helper.py
Labels: bug

#2407 03/14/2025 Production Deploy
  app/__init__.py
  app/assets/javascripts/validation.js
  app/assets/sass/uswds/_data-visualization.scss
  app/assets/sass/uswds/_uswds-theme-custom-styles.scss
  app/main/views/dashboard.py
  app/main/views/index.py
  app/main/views/send.py
  app/main/views/sub_navigation_dictionaries.py
  app/navigation.py
  app/notify_client/user_api_client.py
  app/templates/base.html
  app/templates/components/components/input/template.njk
  app/templates/components/components/label/template.njk
  app/templates/components/file-upload.html
  app/templates/components/header.html
  app/templates/components/radios.html
  app/templates/components/select-input.html
  app/templates/components/textbox.html
  app/templates/partials/templates/guidance-character-count.html
  app/templates/views/about/about.html
  app/templates/views/about/why-text-messaging.html
  app/templates/views/contact.html
  app/templates/views/conversations/conversation.html
  app/templates/views/dashboard/_inbox.html
  app/templates/views/dashboard/_inbox_messages.html
  app/templates/views/dashboard/_totals.html
  app/templates/views/dashboard/dashboard.html
  app/templates/views/dashboard/inbox.html
  app/templates/views/dashboard/most-used-templates.html
  app/templates/views/notify-service-ending.html
  app/templates/views/send-test.html
  app/templates/views/signedout.html
  gulpfile.js
  notifications_utils/request_helper.py
  package-lock.json
  package.json
  poetry.lock
  pyproject.toml
  tests/app/main/views/organizations/test_organizations.py
  tests/app/main/views/service_settings/test_service_settings.py
  tests/app/main/views/test_activity.py
  tests/app/main/views/test_dashboard.py
  tests/app/main/views/test_manage_users.py
  tests/app/main/views/test_register.py
  tests/app/main/views/test_send.py
  tests/app/main/views/test_tour.py
  tests/app/test_navigation.py
  tests/end_to_end/test_landing_and_sign_in_pages.py
  tests/javascripts/validation.test.js
  urls.js
Labels: engineering, Content

#2417 03/17/2025 Production Deploy
  .ds.baseline
  .github/workflows/checks.yml
  .github/workflows/deploy-demo.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy.yml
Labels: engineering

#2420 03/18/2025 Production Deploy
  .github/workflows/checks.yml
  package-lock.json
  package.json
  poetry.lock
  pyproject.toml
Labels: engineering

#2412 2042 no emojis special characters plain language
  app/__init__.py
  app/main/validators.py
  app/main/views/templates.py
  app/templates/views/edit-sms-template.html
  poetry.lock
  tests/app/main/test_validators.py
  tests/app/main/views/test_templates.py
Labels: Content

#2425 2255 - Content update for CSV upload area
  app/templates/views/send.html
Labels: Content

#2447 3/28/2025 Production Deploy
  .ds.baseline
  .github/workflows/checks.yml
  app/__init__.py
  app/assets/javascripts/activityChart.js
  app/assets/javascripts/preventDuplicateFormSubmissions.js
  app/assets/javascripts/validation.js
  app/assets/sass/uswds/_uswds-theme-custom-styles.scss
  app/config.py
  app/main/validators.py
  app/main/views/dashboard.py
  app/main/views/index.py
  app/main/views/send.py
  app/main/views/templates.py
  app/templates/components/components/button/template.njk
  app/templates/components/components/label/template.njk
  app/templates/components/form.html
  app/templates/partials/templates/guidance-optional-content.html
  app/templates/partials/templates/guidance-personalization.html
  app/templates/partials/templates/guidance-send-a-document.html
  app/templates/views/add-service.html
  app/templates/views/check/column-errors.html
  app/templates/views/check/preview.html
  app/templates/views/edit-sms-template.html
  app/templates/views/how-to/edit-and-format-messages.html
  app/templates/views/how-to/index.html
  app/templates/views/notifications/preview.html
  app/templates/views/send-test.html
  app/templates/views/send.html
  app/templates/views/service-settings/link-service-to-organization.html
  app/templates/views/service-settings/set-free-sms-allowance.html
  app/templates/views/service-settings/set-international-sms.html
  app/templates/views/service-settings/set-message-limit.html
  app/templates/views/service-settings/set-rate-limit.html
  app/templates/views/service-settings/set-service-setting.html
  app/templates/views/service-settings/set-sms.html
  app/templates/views/service-settings/sms-prefix.html
  app/templates/views/service-settings/sms-sender/add.html
  app/templates/views/service-settings/sms-sender/edit.html
  notifications_utils/field.py
  notifications_utils/jinja_templates/letter_pdf/_main_css.jinja2
  notifications_utils/sanitise_text.py
  notifications_utils/template.py
  package-lock.json
  package.json
  poetry.lock
  pyproject.toml
  tests/app/main/test_validators.py
  tests/app/main/views/test_send.py
  tests/app/main/views/test_templates.py
  tests/javascripts/validation.test.js
  tests/notifications_utils/test_formatters.py
  tests/notifications_utils/test_markdown.py
  tests/notifications_utils/test_placeholders.py
  tests/notifications_utils/test_recipient_validation.py
  tests/notifications_utils/test_template_types.py
Labels: engineering
